@startuml
skinparam componentStyle rectangle

!include <tupadr3/font-awesome/database>

title Logical View with adapters

[html5-qrcode <external>] as QR
interface " " as QRI
QR - QRI

component Database {
   component [Product DB  <$database{scale=0.33}>] as PDB
   component [Transaction DB  <$database{scale=0.33}>] as TDB
   component [Barcode DB  <$database{scale=0.33}>] as BDB

   BDB -down(0- PDB
   TDB -down(0- PDB
}
interface " " as PDBI #Orange
PDB -down- PDBI
interface " " as BDBI #Orange
BDB -right- BDBI
interface " " as TDBI #Orange
TDB -left- TDBI


[Desktop web interface] as DWI
[Mobile web interface] as MWI
[Operation handler] as OH
interface " " as OHI
OH -down- OHI

[Express Server] as ES
interface " " as ESI
ES -down- ESI

OH -left( TDBI
OH -up( PDBI
OH -right( BDBI


ES -up( OHI

DWI -left( ESI

MWI -right( ESI
QRI )- MWI




skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Courier
@enduml