@startuml
title Process View

participant "html5-qrcode <external>" as QR
participant "Mobile Web interface" as MWI
participant "Watchdog" as WD
participant "Desktop Web interface" as DWI
participant "Express server" as ES
participant "Operation handler" as OH
participant "**Statistics analyzer**" as SA
participant "Products database" as PDB
participant "Transactions database " as TDB
participant "Barcodes database" as BDB




skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Courier

DWI -> ES : Request product list
ES -> OH: Request product list
OH -> PDB: Request product list with name and ID
PDB -> OH: Return product list with name and ID
OH -> ES: Return product list with name and ID
ES -> DWI: Return product list with name and ID
DWI -> ES : Request statistics for a product using the ID and a time interval
ES -> SA : Request statistics for the product ID in the time interval
SA -> PDB : Request the product amount using of the corresponding ID
PDB -> SA : Return the product amount using of the corresponding ID
SA -> TDB : Request all the transaction for the product in the time interval
TDB -> SA : Return all the transaction for the product in the time interval
SA -> SA : Calculate the statistics
SA -> ES : Return the statistics
ES -> DWI : Return the statistics

@enduml